"""Align the vector column with the active embedding model.

Revision ID: 0008
Revises: 0007

Generated by ``python -m app.tools.verify_pgvector --generate-migration``.

Why this is required
--------------------
* The column is 2048 dimensions but the provider reports 1536. Every insert would be rejected.

  Current : halfvec(2048)
  Target  : halfvec(1536)

Indexes dropped and recreated
-----------------------------
A column's type cannot change while an index depends on it, and the HNSW operator
class is type-specific (halfvec_cosine_ops):

* ix_embeddings_hnsw_document_summary
* ix_embeddings_hnsw_clause
* ix_embeddings_hnsw_chunk

Embeddings are deleted, not converted
-------------------------------------
A vector of one width produced by one model cannot be converted to another width
for another model. Padding would invent dimensions the model never produced, and
keeping both is worse than deleting: vectors from two models occupy unrelated
spaces, so a mixed index returns confident nonsense rather than failing.

The rows are fully derived. After applying this::

    cip reindex-embeddings --all

Semantic search is degraded until that completes; keyword search is unaffected.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | None = None
depends_on: str | None = None

TARGET_TYPE = "halfvec"
TARGET_DIM = 1536
PREVIOUS_TYPE = "halfvec"
PREVIOUS_DIM = 2048


def upgrade() -> None:
    bind = op.get_bind()

    if TARGET_TYPE == "halfvec":
        version = bind.execute(
            sa.text("SELECT extversion FROM pg_extension WHERE extname = 'vector'")
        ).scalar_one_or_none()
        if version is None:
            raise RuntimeError("The pgvector extension is not installed.")
        parts = [int(p) for p in str(version).split(".")[:2] if p.isdigit()]
        if parts < [0, 7]:
            raise RuntimeError(
                f"pgvector {version} does not support halfvec (needs >= 0.7.0)."
            )

    existing = bind.execute(sa.text("SELECT count(*) FROM embeddings")).scalar_one()
    if existing:
        print(  # noqa: T201 - alembic's channel to the operator
            f"  -> discarding {existing} embedding(s); they cannot be converted. "
            "Run `cip reindex-embeddings --all` after this migration."
        )

    op.execute("DROP INDEX IF EXISTS ix_embeddings_hnsw_document_summary")
    op.execute("DROP INDEX IF EXISTS ix_embeddings_hnsw_clause")
    op.execute("DROP INDEX IF EXISTS ix_embeddings_hnsw_chunk")

    op.execute("DELETE FROM embeddings")
    op.execute(
        f"ALTER TABLE embeddings ALTER COLUMN embedding "
        f"TYPE {TARGET_TYPE}({TARGET_DIM})"
    )
    op.execute(f"ALTER TABLE embeddings ALTER COLUMN dim SET DEFAULT {TARGET_DIM}")

    op.execute(
        """
        CREATE INDEX ix_embeddings_hnsw_document_summary
        ON embeddings USING hnsw (embedding halfvec_cosine_ops)
        WITH (m = 16, ef_construction = 64)
        WHERE level = 'document_summary'
        """
    )
    op.execute(
        """
        CREATE INDEX ix_embeddings_hnsw_clause
        ON embeddings USING hnsw (embedding halfvec_cosine_ops)
        WITH (m = 16, ef_construction = 64)
        WHERE level = 'clause'
        """
    )
    op.execute(
        """
        CREATE INDEX ix_embeddings_hnsw_chunk
        ON embeddings USING hnsw (embedding halfvec_cosine_ops)
        WITH (m = 16, ef_construction = 64)
        WHERE level = 'chunk'
        """
    )


def downgrade() -> None:
    """Equally destructive, for the same reason - see the module docstring."""
    op.execute("DROP INDEX IF EXISTS ix_embeddings_hnsw_document_summary")
    op.execute("DROP INDEX IF EXISTS ix_embeddings_hnsw_clause")
    op.execute("DROP INDEX IF EXISTS ix_embeddings_hnsw_chunk")

    op.execute("DELETE FROM embeddings")
    op.execute(
        f"ALTER TABLE embeddings ALTER COLUMN embedding "
        f"TYPE {PREVIOUS_TYPE}({PREVIOUS_DIM})"
    )
    op.execute(f"ALTER TABLE embeddings ALTER COLUMN dim SET DEFAULT {PREVIOUS_DIM}")

    op.execute(
        """
        CREATE INDEX ix_embeddings_hnsw_document_summary
        ON embeddings USING hnsw (embedding halfvec_cosine_ops)
        WITH (m = 16, ef_construction = 64)
        WHERE level = 'document_summary'
        """
    )
    op.execute(
        """
        CREATE INDEX ix_embeddings_hnsw_clause
        ON embeddings USING hnsw (embedding halfvec_cosine_ops)
        WITH (m = 16, ef_construction = 64)
        WHERE level = 'clause'
        """
    )
    op.execute(
        """
        CREATE INDEX ix_embeddings_hnsw_chunk
        ON embeddings USING hnsw (embedding halfvec_cosine_ops)
        WITH (m = 16, ef_construction = 64)
        WHERE level = 'chunk'
        """
    )
