"""Canonical Document Model: schema and builder."""

from app.ai.cdm.models import (
    CanonicalDocument,
    ContentBlock,
    Coordinates,
    CrossReference,
    DocumentList,
    DocumentMetadata,
    DocumentStatistics,
    Footnote,
    HeaderFooter,
    Image,
    ListItem,
    NormalizedDocument,
    Page,
    Paragraph,
    QualityMetrics,
    ReadingOrderEntry,
    Section,
    Signature,
    Table,
    TableCell,
)

__all__ = [
    "CanonicalDocument",
    "ContentBlock",
    "Coordinates",
    "CrossReference",
    "DocumentList",
    "DocumentMetadata",
    "DocumentStatistics",
    "Footnote",
    "HeaderFooter",
    "Image",
    "ListItem",
    "NormalizedDocument",
    "Page",
    "Paragraph",
    "QualityMetrics",
    "ReadingOrderEntry",
    "Section",
    "Signature",
    "Table",
    "TableCell",
]
